@startuml sample

skinparam shadowing false
skinparam linetype ortho

entity "ユーザー" as user {
    + ユーザーID [PK]
    ---
    * ユーザー名
}

entity "支出計画" as expenditure_plan {
    + 支出計画ID [PK]
    ---
    * ユーザーID [FK]
    * 計画開始日
    * 計画終了日
    * 月収入
}

entity "支出計画明細" as expenditure_plan_detail {
    + 支出計画ID [PK]
    ---
    * 消費割合
    * 投資割合
    * 浪費割合
}

entity "支出" as expenditure {
    + 支出ID [PK]
    ---
    * ユーザーID [FK]
    * 支出日時
    * 支出額
    * 支出分類
}

user ||-down-o{ expenditure_plan
user ||-right-o{ expenditure
expenditure_plan ||-right-|| expenditure_plan_detail
@enduml